# Generated by Django 4.0.5 on 2022-09-30 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('My_Video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='collected_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
