# Generated by Django 4.0.5 on 2022-10-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Video', '0003_collection_dislikes_remove_collection_likes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
