# Generated by Django 4.0.5 on 2022-10-01 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('My_Video', '0004_delete_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='likes',
        ),
        migrations.AddField(
            model_name='collection',
            name='likes',
            field=models.ManyToManyField(related_name='collection_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
