# Generated by Django 4.0.5 on 2022-10-01 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('My_Video', '0005_remove_collection_likes_collection_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='collection',
            name='dislikes',
            field=models.ManyToManyField(related_name='collection_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
